version: "3.3"

services:
  wp:
    image: wordpress:latest
    volumes:
      [
        "./wp/:/var/www/html",
        "./wp-php/z_dishlist.ini:/usr/local/etc/php/conf.d/z_dishlist.ini",
      ]
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 74.208.228.35:3306
      WORDPRESS_DB_USER: wp_h8m3k
      WORDPRESS_DB_PASSWORD: 5_Vl28beTU
      WORDPRESS_DB_NAME: wp_v1sxv
      WORDPRESS_DEBUG: 1
